### ISSUE TITLE
dev web client assumes pass is scheduled when it might not be - causing the UI to not work

### ISSUE THREAD

**Issue by cshields** [satnogs/satnogs-client#133]
I'm just now catching up on the past weeks work on the client and this should be an easy fix but I don't have time to dive into it at the moment - so I'm filing to make record of it.

For the web client in app.py, scheduled_pass_check connects to the task feeder which is always alive. If it connects (which it will), it is assumed that there is a scheduled pass and tries to load the json - which is not always going to be the case. Somewhere here the process will stall, causing http://update_status to hang and making the webui to just not work (other menu bar links won't even load).

**Comment by GVardakis** [comment]
If no observations are scheduled the task feeder thread will return an empty list as it is also implied by the debug messages printed on the console : 

2016-07-09 18:20:15,103 - satnogsclient - DEBUG - Sending message: Requesting scheduled observations

2016-07-09 18:20:15,104 - satnogsclient - DEBUG - Received message: []

I cannot see it stalling at any point, too. Are you sure you are running the latest dev branch?

**Comment by cshields** [comment]
Yes, just updated today.

2016-07-09 11:29:27,829 - satnogsclient - DEBUG - Opening TCP socket: 127.0.0.1:5005
2016-07-09 11:29:27,830 - satnogsclient - ERROR - Cannot connect to socket 127.0.0.1:5005
2016-07-09 11:29:27,830 - satnogsclient - DEBUG - Opening TCP socket: 127.0.0.1:5011
2016-07-09 11:29:27,830 - satnogsclient - DEBUG - Sending message: Requesting scheduled observations

... and this is where it stalls

**Comment by cshields** [comment]
...and when the browser times out:

2016-07-09 11:31:10,439 - satnogsclient.web.app - ERROR - Exception on /update_status [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/satnogsclient-0.2.5-py2.7.egg/satnogsclient/web/app.py", line 39, in get_status_info
    scheduled_pass_json = scheduled_pass_sock.send("Requesting scheduled observations\n")
  File "/usr/local/lib/python2.7/dist-packages/satnogsclient-0.2.5-py2.7.egg/satnogsclient/observer/commsocket.py", line 77, in send
    response = self.s.recv(self._TASKS_BUFFER_SIZE)
error: [Errno 104] Connection reset by peer

**Comment by cshields** [comment]
The app thread *tries* to reach the task feeder (port 5011), connect fine but does not get an answer when it sends the text (see below for the packet dump)...

Oddly enough - I can start the client and connect to 5011 with telnet, feed it a \n and I do get the expected [].

<img width="1316" alt="screenshot 2016-07-09 12 29 06" src="https://cloud.githubusercontent.com/assets/225283/16708964/0dc17e7c-45d1-11e6-8236-289571453e32.png">

**Comment by GVardakis** [comment]
That's weird. Could it be a firewall issue?

**Comment by cshields** [comment]
No, else the connect would not work (SYN/ACK).

So - I found the fix but I don't yet have a full grasp on the problem. Python's socket send() function does not guarantee delivery of the full payload. For whatever reason app.py is sending the whole packet but the task feeder is not getting it all. (it is well within buffer)

2 options to fix this:

1 commsocket.py line 76 change self.s.send(message) to self.s.sendall(message)

or

2 change the message sent to something shorter ("\n" worked for me)

I would opt for the former given that there may be other future bugs this might solve, but I don't know the implications of not just using send(). Tagging @jinxcat in this.
