### ISSUE TITLE
Error on time packets

### ISSUE THREAD

**Issue by ppapadeas** [satnogs/satnogs-client#145]
1801c00000051009030600c0
I should see that
I should see that also {'ser_type': 9, 'ack': 0, 'data': bytearray(b''), 'ser_subtype': 3, 'dest_id': 6, 'type': 1, 'app_id': 1, 'size': 0}
127.0.0.1 - - [17/Jul/2016 16:11:59] "POST /command HTTP/1.1" 200 -
sending to conn  ["(dp1\nS'ser_type'\np2\nI9\nsS'ack'\np3\nI0\nsS'data'\np4\nc__builtin__\nbytearray\np5\n(V\nS'latin-1'\ntRp6\nsS'ser_subtype'\np7\nI3\nsS'dest_id'\np8\nI6\nsS'type'\np9\nI1\nsS'app_id'\np10\nI1\nsS'size'\np11\nI0\ns."]
This is a packet: �]qU�(dp1
S'ser_type'
p2
I9
sS'ack'
p3
I0
sS'data'
p4
c__builtin__
bytearray
p5
(V
S'latin-1'
tRp6
sS'ser_subtype'
p7
I3
sS'dest_id'
p8
I6
sS'type'
p9
I1
sS'app_id'
p10
I1
sS'size'
p11
I0
s.qa.
(dp1
S'ser_type'
p2
I9
sS'ack'
p3
I0
sS'data'
p4
c__builtin__
bytearray
p5
(V
S'latin-1'
tRp6
sS'ser_subtype'
p7
I3
sS'dest_id'
p8
I6
sS'type'
p9
I1
sS'app_id'
p10
I1
sS'size'
p11
I0
s.
Received ECSS formated  {'ack': 0, 'data': bytearray(b''), 'dest_id': 6, 'app_id': 1, 'ser_subtype': 3, 'type': 1, 'ser_type': 9, 'size': 0}
[2016-07-17 16:11:59,894] ERROR in app: Exception on /control_rx [POST]
Traceback (most recent call last):
  File "/home/liknus/.virtualenvs/satnogs-client/lib/python2.7/site-packages/Flask-0.11.1-py2.7.egg/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/liknus/.virtualenvs/satnogs-client/lib/python2.7/site-packages/Flask-0.11.1-py2.7.egg/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/liknus/.virtualenvs/satnogs-client/lib/python2.7/site-packages/Flask-0.11.1-py2.7.egg/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/liknus/.virtualenvs/satnogs-client/lib/python2.7/site-packages/Flask-0.11.1-py2.7.egg/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/liknus/.virtualenvs/satnogs-client/lib/python2.7/site-packages/Flask-0.11.1-py2.7.egg/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/liknus/git/satnogs-client/satnogsclient/web/app.py", line 84, in get_control_rx
    res = packet.ecss_logic(ecss_dict)
  File "/home/liknus/git/satnogs-client/satnogsclient/upsat/packet.py", line 440, in ecss_logic
    day = ecss_dict['data'][0]
IndexError: bytearray index out of range
2016-07-17 16:11:59,894 - satnogsclient.web.app - ERROR - Exception on /control_rx [POST]
Traceback (most recent call last):
  File "/home/liknus/.virtualenvs/satnogs-client/lib/python2.7/site-packages/Flask-0.11.1-py2.7.egg/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/liknus/.virtualenvs/satnogs-client/lib/python2.7/site-packages/Flask-0.11.1-py2.7.egg/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/liknus/.virtualenvs/satnogs-client/lib/python2.7/site-packages/Flask-0.11.1-py2.7.egg/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/liknus/.virtualenvs/satnogs-client/lib/python2.7/site-packages/Flask-0.11.1-py2.7.egg/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/liknus/.virtualenvs/satnogs-client/lib/python2.7/site-packages/Flask-0.11.1-py2.7.egg/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/liknus/git/satnogs-client/satnogsclient/web/app.py", line 84, in get_control_rx
    res = packet.ecss_logic(ecss_dict)
  File "/home/liknus/git/satnogs-client/satnogsclient/upsat/packet.py", line 440, in ecss_logic
    day = ecss_dict['data'][0]
IndexError: bytearray index out of range

**Comment by ppapadeas** [comment]
@nchronas can you check this?
