### ISSUE TITLE
On searching file for uploading to network, if there is a file without "_" char, post_data task throws an error.

### ISSUE THREAD

**Issue by adamkalis** [satnogs/satnogs-client#271]
On searching file for uploading to network, if there is a file without "_" char, post_data tasks is terminated with an error.

017-05-26 12:21:42,019 - apscheduler.executors.default - ERROR - Job "post_data (trigger: interval[0:02:00], next run at: 2017-05-26 10:23:41 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/satnogsclient-0.3-py2.7.egg/satnogsclient/scheduler/tasks.py", line 91, in post_data
    observation_id = f.split('_')[1]
IndexError: list index out of range

Solution should be to ignore any file that doesn't follow  <satnogs|waterfall>_<obsID>_<time>.<fileext> format.

**Comment by adamkalis** [comment]
#288 fixes this issue
