### ISSUE TITLE
Handle non graceful exit in satnogs-poller

### ISSUE THREAD

**Issue by johngian** [satnogs/satnogs-client#58]
We need to make sure that every time satnogs-poller encounters an error no stale processes are left.

**Comment by cshields** [comment]
I was tempted to make this its own issue, but ran into this upon completion of a pass today

```
2016-02-06 02:11:36,147 - satnogsclient - INFO - Tracking stopped.
2016-02-06 02:11:36,148 - satnogsclient - DEBUG - Observer data: {'lat': 39.236, 'lon': -86.305, 'elev': 280.0}
2016-02-06 02:11:36,148 - satnogsclient - DEBUG - Satellite data: {'tle2': u'2 33493  98.2312 250.2712 0014930 285.8502  74.1111 14.94445384381413', 'tle1': u'1 33493U 09002B   16036.52528305  .00001673  00000-0  16085-3 0  9999', 'tle0': u'PRISM (HITOMI)'}
2016-02-06 02:11:36,149 - satnogsclient - DEBUG - Calculated data: {'rng_vlct': 6966.7841796875, 'alt': 0.0005696563748642802, 'az': 3.516078472137451, 'rng': 2863406.0, 'ok': True}
2016-02-06 02:11:36,150 - satnogsclient - INFO - Stop receiver
2016-02-06 02:11:36,152 - apscheduler.executors.default - INFO - Job "spawn_receiver (trigger: date[2016-02-06 01:58:37 UTC], next run at: 2016-02-06 01:58:37 UTC)" executed successfully
2016-02-06 02:11:36,150 - satnogsclient - DEBUG - Initial frequency: 437250000
2016-02-06 02:11:36,155 - satnogsclient - DEBUG - Rigctld msg: F 437239838.883

2016-02-06 02:11:36,156 - satnogsclient - DEBUG - Sending message: F 437239838.883

Exception in thread Thread-22:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "build/bdist.linux-armv7l/egg/satnogsclient/observer/worker.py", line 101, in _communicate_tracking_info
    self.send_to_socket(p, sock)
  File "build/bdist.linux-armv7l/egg/satnogsclient/observer/worker.py", line 135, in send_to_socket
    sock.send(msg)
  File "build/bdist.linux-armv7l/egg/satnogsclient/observer/commsocket.py", line 66, in send
    response = self.s.recv(self._BUFFER_SIZE)
error: [Errno 104] Connection reset by peer

2016-02-06 02:11:36,207 - satnogsclient - INFO - Closing socket: <socket._socketobject object at 0x760ba490>
```

Now, thankfully, it keeps running fine after that..
